-- DDL for TB_METADATA table
CREATE TABLE TB_METADATA (
    CATEGORY VARCHAR2(50) PRIMARY KEY,
    CURRENT_VERSION NUMBER NOT NULL,
    LAST_UPDATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Insert initial data
INSERT INTO TB_METADATA (CATEGORY, CURRENT_VERSION) VALUES ('WHISKEY_LIST', 1);